apps/animals_feed/urls.py
from django.urls import path

from apps.animals_feed import views


app_name = "animals_feed"

urlpatterns: list[path] = [
    path("", views.feed, name="index"),
    path("<int:card_id>/", views.card, name="card"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("apps.home_page.urls")),
    path("admin/", admin.site.urls),
    path("crm/", include("apps.animals_crm.urls")),
    path("feed/", include("apps.animals_feed.urls")),
    path("blog/", include("apps.blog.urls")),
    path("users/", include("apps.users.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/animals_feed/views/card.py
from django.shortcuts import render

from apps.animals_crm import models


def card(request, card_id):
    # animal = get_object_or_404(models.AnimalCard, pk=card_id)
    animal = models.AnimalCard.objects.get(pk=card_id)
    animal_photo = animal.photos.order_by("-modified_at")
    animal_comment = models.AnimalComment.objects.filter(animal=animal).order_by("-created_at")
    context = {"title": "temp", "animal": animal, "animal_photo": animal_photo, "comments": animal_comment}

    return render(request=request, template_name="feed/card.html", context=context)

apps/animals_feed/views/feed.py
from django.shortcuts import render

from apps.helpers.get_page_obj import get_page_obj
from apps.animals_crm import models


def feed(request):
    animal_cards = models.AnimalCard.objects.order_by("-modified_at")

    page_obj, posts = get_page_obj(request, animal_cards, 3)

    context = {"title": "Feed", "posts": posts, "page_obj": page_obj}

    return render(request=request, template_name="feed/feed.html", context=context)

apps/templates/feed/card.html
{% extends "base.html" %}
{% block Head %}
    <link rel="stylesheet"
          href="https://unpkg.com/swiper/swiper-bundle.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/feed/card.css' %}">
{% endblock Head %}
{% block Body %}
    <div style="margin-top: 30px">
        <div style="margin: auto" class="col-md-4 mb-4">
            <div class="card text-center">
                <div class="card-body">
                    <div class="pagination" style="position: absolute; top: 10px; right: 10px">
                        <a class="page-link" href="{% url 'animals_feed:index' %}"> << Back << </a>
                    </div>
                    <p style="text-align: left; font-size: 28px">
                        {{ animal }}, {{ animal.age }}
                        {% if animal.age == 1 %}
                            year
                        {% else %}
                            years
                        {% endif %}
                    </p>
                    <p style="text-align: left; font-size: 15px; margin-top: -15px">{{ animal.description }}</p>
                    <!-- Swiper -->
                    <div class="swiper-container">
                        <div class="swiper-wrapper">
                            {% for img in animal_photo %}
                                <div class="swiper-slide">
                                    <img src="{{ img.image.url }}" alt="{{ animal }}">
                                </div>
                            {% endfor %}
                        </div>
                        <!-- Добавьте элементы навигации и пагинации, если нужно -->
                        <div class="swiper-button-next"></div>
                        <div class="swiper-button-prev"></div>
                        <div class="swiper-pagination"></div>
                    </div>
                    <p style="margin-top: 20px;
                              display: flex;
                              justify-content: space-between;
                              font-size: 18px;
                              margin-bottom: 10px">
                        Comments ({{ animal.comments.count }}):
                        <span style="font-size: 20px">{{ animal.created_at }}</span>
                    </p>
                    {% for com in comments %}
                        <div style="text-align: left; margin-left: 20px; font-size: 16px">
                            <p style="margin-top: -15px; font-size: 14px">{{ com.comment_text }}</p>
                            <p style="margin-top: -20px; font-size: 11px">{{ com.created_at }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <!-- Initialize Swiper -->
    <script>
    var swiper = new Swiper('.swiper-container', {
      slidesPerView: 1,
      spaceBetween: 10,
      loop: true,
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
    });
    </script>
{% endblock Body %}

apps/templates/feed/feed.html
{% extends "base.html" %}
{% block Head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/feed/feed.css' %}">
{% endblock Head %}
{% block Body %}
    <h2>Its a feed!</h2>
    {% for animal in posts %}
        <div style="margin: auto" class="col-md-4 mb-4">
            <div class="card text-center">
                <div class="card-body">
                    <p style="text-align: left; font-size: 28px">
                        <a href="{% url 'animals_feed:card' animal.pk %}">{{ animal }}</a>, {{ animal.age }}
                        {% if animal.age == 1 %}
                            year
                        {% else %}
                            years
                        {% endif %}
                    </p>
                    <p style="text-align: left; font-size: 14px; margin-top: -15px">
                        {% if animal.description|length > 100 %}
                            {{ animal.description|slice:":100" }}...
                        {% else %}
                            {{ animal.description }}
                        {% endif %}
                    </p>
                    {% if animal.last_photo %}
                        <img style="max-width: 100%;
                                    max-height: 300px;
                                    margin-bottom: 20px"
                             src="{{ animal.last_photo.image.url }}"
                             alt="{{ animal }}">
                    {% endif %}
                    <p style="display: flex;
                              justify-content: space-between;
                              font-size: 16px;
                              margin-bottom: 0">
                        <a href="{% url 'animals_feed:card' animal.pk %}">Comments ({{ animal.comments.count }})</a>
                        <span style="font-size: 14px">{{ animal.created_at }}</span>
                    </p>
                    {% if animal.last_comment %}
                        <div style="text-align: left; margin-left: 30px">
                            <p style="margin-bottom: -5px; font-size: 14px">{{ animal.last_comment }}</p>
                            <p style="margin: 0; font-size: 11px">{{ animal.last_comment.created_at }}</p>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
    <div class="d-flex justify-content-center mt-4">
        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1"><<</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"><</a>
                    </li>
                {% endif %}
                <li class="page-item disabled">
                    <span class="page-link">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
                </li>
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">></a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">>></a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock Body %}