apps/animals_crm/urls.py
from django.urls import path
from . import views


app_name = "crm"

urlpatterns: list[path] = [
    path("", views.crm_index, name="crm"),
    path("new-card", views.new_card, name="new_card"),
    # work with 1 card
    path("edit/<int:card_id>", views.edit_card, name="edit_card"),
    path("delete/<int:card_id>", views.delete_card, name="delete_card"),
]

apps/blog/urls.py
from django.urls import path
from apps.blog import views

app_name = "blog"

urlpatterns: list[path] = [
    path("", views.index, name="index"),
    path("new_post/", views.new_post, name="new_post"),
    path("edit_post/<int:post_id>", views.edit_post, name="edit_post"),
    path("delete_post/<int:post_id>", views.delete_post, name="delete_post"),
    path("post_deleted/", views.post_deleted, name="post_deleted"),
]

apps/home_page/urls.py
from apps.home_page import views
from django.urls import path

app_name = "home_page"

urlpatterns = [
    path("", views.index, name="home"),
]

apps/users/urls.py
from apps.users import views
from django.urls import path, include

app_name = "users"

urlpatterns: list[path] = [
    path("", include("django.contrib.auth.urls")),
    path("register/", views.register, name="register"),
    path("profile/", views.profile, name="profile"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("apps.home_page.urls")),
    path("admin/", admin.site.urls),
    path("crm/", include("apps.animals_crm.urls")),
    path("feed/", include("apps.animals_feed.urls")),
    path("blog/", include("apps.blog.urls")),
    path("users/", include("apps.users.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="description" content="Do Not Leave Animals">
        <meta name="keywords" content="DNLA">
        <meta charset="UTF-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
              crossorigin="anonymous">
        <title>DNLA | {{ title }}</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        {% block Head %}
        {% endblock Head %}
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-light">
                <a class="navbar-brand" href="{% url 'home_page:home' %}">DNLA</a>
                <button class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'animals_feed:index' %}">Feed</a>
                        </li>
                        {% if user.is_staff or user.is_superuser %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'crm:crm' %}">CRM</a>
                            </li>
                        {% endif %}
                    </ul>
                    <div class="ms-auto">
                        <div class="nav-item">
                            {% if user.is_authenticated %}
                                Hello, {{ user.username }}.
                                <form action="{% url 'users:logout' %}"
                                      method="post"
                                      style="display: inline">
                                    {% csrf_token %}
                                    <button type="submit"
                                            style="background: none;
                                                   border: none;
                                                   padding: 0;
                                                   color: #13ca17;
                                                   text-decoration: none;
                                                   cursor: pointer">Log out</button>
                                </form>
                            {% else %}
                                <a href="{% url 'users:register' %}">Register</a>
                                <a href="{% url 'users:login' %}">Log in</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <div style="margin-top: 70px" class="body flex-grow-1">
            {% block Body %}
            {% endblock Body %}
        </div>
        <footer>
            <div class="footer-content">
                <div class="footer-left">
                    <ul style="list-style: none; padding: 0; margin: 0;">
                        <li>
                            <a class="nav-nav" href="{% url 'home_page:home' %}">Home</a>
                        </li>
                        <li>
                            <a class="nav-nav" href="{% url 'blog:index' %}">Blog</a>
                        </li>
                        <li>
                            <a class="nav-nav" href="{% url 'animals_feed:index' %}">Feed</a>
                        </li>
                    </ul>
                    <nav class="footer-nav">
                    </nav>
                </div>
                <div class="footer-right">
                    <div style="margin-right: -10px" class="footer-social">
                        <a href="https://instagram.com"><i class="fab fa-instagram"></i> Instagram</a>
                        <a href="https://facebook.com"><i class="fab fa-facebook"></i> Facebook</a>
                        <a href="https://telegram.org"><i class="fab fa-telegram"></i> Telegram</a>
                    </div>
                    <div class="footer-contact">
                        <p>Тел: +38 (063) 000-00-00</p>
                        <p>Email: support@localhost</p>
                    </div>
                </div>
            </div>
            <p class="footer-copyright">© 2024 Do Not Leave Animals. All rights reserved.</p>
        </footer>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </body>
</html>