apps/blog/urls.py
from django.urls import path
from apps.blog import views

app_name = "blog"

urlpatterns: list[path] = [
    path("", views.index, name="index"),
    path("new_post/", views.new_post, name="new_post"),
    path("edit_post/<int:post_id>", views.edit_post, name="edit_post"),
    path("delete_post/<int:post_id>", views.delete_post, name="delete_post"),
    path("post_deleted/", views.post_deleted, name="post_deleted"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("apps.home_page.urls")),
    path("admin/", admin.site.urls),
    path("crm/", include("apps.animals_crm.urls")),
    path("feed/", include("apps.animals_feed.urls")),
    path("blog/", include("apps.blog.urls")),
    path("users/", include("apps.users.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models


class Post(models.Model):
    """
    Model Form
    """

    title = models.CharField(max_length=60)
    description = models.TextField(blank=True)
    photo = models.ImageField(upload_to="photos/blog", null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

apps/blog/forms.py
from django import forms
from apps.blog.models import Post


class PostForm(forms.ModelForm):
    """
    Form for creating a post
    """

    class Meta:
        model = Post
        fields = ["title", "description", "photo"]

apps/blog/views/delete_post.py
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect

from ..models import Post


def delete_post(request, post_id):
    """
    Delete a post
    :param request: request object
    :param post_id: post id
    :return: redirect or render page
    """
    if request.user.is_staff:
        post = Post.objects.get(id=post_id)

        if request.method == "POST":
            post.delete()
            return redirect("blog:post_deleted")
        else:
            return render(
                request=request, template_name="blog/delete_post.html", context={"post": post, "title": "Delete Post"}
            )
    else:
        return HttpResponseForbidden()

apps/blog/views/edit_post.py
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

from apps.blog.forms import PostForm
from apps.blog.models import Post


def edit_post(request, post_id):
    """
    Edit post on blog page
    :param request: request object
    :param post_id: post id
    :return: render edit post page or redirect to index page with posts
    """
    if request.user.is_staff:
        post = Post.objects.get(id=post_id)

        if request.method == "POST":
            form = PostForm(request.POST, request.FILES, instance=post)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect("/blog/")
        elif request.method == "GET":
            context = {"title": "Edit Post", "form": PostForm(instance=post), "post_id": post_id}
            return render(request=request, template_name="blog/edit_post.html", context=context)
    else:
        return HttpResponseForbidden()

apps/blog/views/index.py
from django.shortcuts import render

from apps.helpers.get_page_obj import get_page_obj
from apps.blog.models import Post


def index(request):
    """
    Blog main index page
    :param request: request object
    :return: render index page
    """
    page_obj, posts = get_page_obj(request, Post.objects.order_by("-date"), 3)

    context = {"title": "Blog", "posts": posts, "page_obj": page_obj, "is_staff": request.user.is_staff}

    return render(request, "blog/index.html", context)

apps/blog/views/new_post.py
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

from apps.blog.forms import PostForm


def new_post(request):
    """
    Create new post to blog page
    :param request: request object
    :return: render new post page or redirect to index page with new post
    """
    if request.user.is_staff:
        context = {"title": "New Post", "form": PostForm}
        if request.method == "POST":
            form = PostForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect("/blog/")
        elif request.method == "GET":
            return render(request=request, template_name="blog/new_post.html", context=context)
    else:
        return HttpResponseForbidden()

apps/blog/views/post_deleted.py
from django.shortcuts import render
from django.http import HttpResponseForbidden


def post_deleted(request) -> render:
    """
    Render post deleted page
    :param request: request object
    :return: render post deleted page
    """
    if request.user.is_staff:
        context = {"title": "Post Deleted"}
        return render(request=request, template_name="blog/post_deleted.html", context=context)
    else:
        return HttpResponseForbidden()

apps/templates/blog/delete_post.html
{% extends "base.html" %}
{% load static %}
{% block Head %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/blog/index.css' %}">
{% endblock Head %}
{% block Body %}
    <div style="margin-top: 100px" class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 mb-4">
                <div class="card text-center shadow">
                    <div class="card-header bg-danger text-white">
                        <h5>Confirm Deletion</h5>
                    </div>
                    <div style="margin-top: 20px" class="card-body">
                        <p>Are you sure you want to delete the post "{{ post.title }}"?</p>
                        <form method="post" action="{% url 'blog:delete_post' post.id %}">
                            {% csrf_token %}
                            <div class="d-flex justify-content-center mt-4">
                                <button class="btn btn-danger" type="submit">Yes</button>
                                <a href="{% url 'blog:edit_post' post.id %}"
                                   class="btn btn-success ml-3">No</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock Body %}

apps/templates/blog/edit_post.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block Head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/blog/edit_post.css' %}">
{% endblock Head %}
{% block Body %}
    <div style="margin-top: 30px;" class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 mb-4">
                <div class="card text-center shadow">
                    <div class="card-header">
                        <h5>Edit Post</h5>
                    </div>
                    <div class="card-body">
                        <form method="post"
                              enctype="multipart/form-data"
                              action="{% url 'blog:edit_post' post_id %}">
                            {% csrf_token %}
                            <div class="form-group">{{ form|crispy }}</div>
                            <!-- Buttons Section -->
                            <div class="d-flex justify-content-center mt-4">
                                <button class="btn btn-primary" type="submit">Save</button>
                                <a class="btn btn-danger ml-3"
                                   href="{% url 'blog:delete_post' post_id %}">Delete</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock Body %}

apps/templates/blog/index.html
{% extends "base.html" %}
{% block Head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/blog/index.css' %}">
{% endblock Head %}
{% block Body %}
    <h2 class="blog-title">
        It's a blog!
        {% if is_staff %}
            <a class="new-post" href="{% url 'blog:new_post' %}">New post</a>
        {% endif %}
    </h2>
    {% for post in posts %}
        <div style="margin: auto" class="col-md-4 mb-4">
            <div class="card text-center">
                <div class="card-body">
                    <p style="text-align: left; font-size: 28px">{{ post.title }}</p>
                    <p style="text-align: left; font-size: 14px; margin-top: -15px">{{ post.description }}</p>
                    {% if post.photo %}
                        <img style="max-width: 100%;
                                    max-height: 300px;
                                    margin-bottom: 20px"
                             src="{{ post.photo.url }}"
                             alt="Image for {{ post.title }}">
                    {% endif %}
                    <div style="text-align: right">
                        <h5>{{ post.date }}</h5>
                    </div>
                    {% if is_staff %}
                        <a class="btn btn-primary" href="{% url 'blog:edit_post' post.id %}">Edit</a>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
    <div class="d-flex justify-content-center mt-4">
        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1"><<</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"><</a>
                    </li>
                {% endif %}
                <li class="page-item disabled">
                    <span class="page-link">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
                </li>
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">></a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">>></a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock Body %}

apps/templates/blog/new_post.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block Head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/blog/index.css' %}">
{% endblock Head %}
{% block Body %}
    <div style="margin-top: 30px;" class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 mb-4">
                <div class="card text-center shadow">
                    <div class="card-header bg-success text-white">
                        <h5>Create New Post</h5>
                    </div>
                    <div class="card-body">
                        <form method="post"
                              enctype="multipart/form-data"
                              action="{% url 'blog:new_post' %}">
                            {% csrf_token %}
                            <div class="form-group">{{ form|crispy }}</div>
                            <!-- Buttons Section -->
                            <div class="d-flex justify-content-center mt-4">
                                <button class="btn btn-success" type="submit">Save Post</button>
                                <a class="btn btn-primary ml-3" href="{% url 'blog:index' %}">Back</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock Body %}

apps/templates/blog/post_deleted.html
{% extends "base.html" %}
{% load static %}
{% block Head %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/blog/index.css' %}">
{% endblock Head %}
{% block Body %}
    <div style="margin-top: 100px" class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 mb-4">
                <div class="card text-center shadow">
                    <div class="card-header bg-danger text-white">
                        <h5>Post Deleted</h5>
                    </div>
                    <div class="card-body">
                        <a class="btn btn-success" href="{% url 'blog:index' %}">Blog Page</a>
                        <a class="btn btn-success ml-3" href="{% url 'blog:new_post' %}">New Post</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock Body %}